**1. Programar un algoritmo de multiplicación de matrices cuadradas de igual tamaño. Las matrices se generarán de forma aleatoria mediante la función numpy.random.rand. La multiplicación de matrices debe realizarse en python puro, sin utilizar las funciones de numpy.**

In [18]:
import numpy as np

def generar_matriz_aleatoria(tamaño):
    """
    Genera una matriz cuadrada de tamaño dado con valores aleatorios entre 0 y 1.
    """
    return np.random.rand(tamaño, tamaño)

def multiplicar_matrices(matriz1, matriz2):
    """
    Multiplica dos matrices cuadradas de igual tamaño sin usar numpy.
    """
    tamaño = len(matriz1)
    resultado = [[0] * tamaño for _ in range(tamaño)]

    # Realizar la multiplicación de matrices
    for i in range(tamaño):
        for j in range(tamaño):
            for k in range(tamaño):
                resultado[i][j] += matriz1[i][k] * matriz2[k][j]

    return resultado

# Parámetros
tamaño = 3  # Cambia el tamaño de la matriz según sea necesario

# Generar matrices aleatorias
matriz1 = generar_matriz_aleatoria(tamaño)
matriz2 = generar_matriz_aleatoria(tamaño)

# Convertir las matrices de numpy a listas de listas para la multiplicación
matriz1_lista = matriz1.tolist()
matriz2_lista = matriz2.tolist()

# Multiplicar las matrices
resultado = multiplicar_matrices(matriz1_lista, matriz2_lista)

# Imprimir las matrices y el resultado
print("Matriz 1:")
for fila in matriz1_lista:
    print(fila)

print("\nMatriz 2:")
for fila in matriz2_lista:
    print(fila)

print("\nResultado de la multiplicación:")
for fila in resultado:
    print(fila)

Matriz 1:
[0.5569335251967981, 0.8714711368184132, 0.5857809783164213]
[0.43284614116485576, 0.46299707620073893, 0.11739478636461143]
[0.15045348063781738, 0.9234283119657394, 0.733795311391338]

Matriz 2:
[0.052589452446539786, 0.18044473408648232, 0.8084973847321417]
[0.2706214526538223, 0.3156797389552649, 0.9140403388679231]
[0.4996522882339328, 0.9729327041278393, 0.6735577534053574]

Resultado de la multiplicación:
[0.5578144203506094, 0.9455269740959151, 1.6413963915447811]
[0.20671665652718565, 0.33848082994318396, 0.852225146113816]
[0.6244542838032676, 1.0325896033596265, 1.4599454942090562]


**2. Realizar una versión por bloques del anterior algoritmo. Las matrices se deben generar teniendo en cuenta dos parámetros: “cantidad de bloques” (N) y “medida de los bloques” (M). Siguiendo esta lógica, cada matriz estará compuesta por NxN bloques de MxM unidades. Cada operación que se desee ejecutar en paralelo debe ejecutarse dentro de una función. Estos parámetros han de ser fácilmente configurables.**

In [2]:
def generar_matriz_aleatoria_por_bloques(N, M):
    """
    Genera una matriz NxN bloques de MxM unidades con valores aleatorios entre 0 y 1.
    """
    return np.random.rand(N * M, N * M)

def multiplicar_bloques(matriz1, matriz2, N, M):
    """
    Multiplica matrices usando el enfoque por bloques.
    """
    tamaño = N * M
    resultado = [[0] * tamaño for _ in range(tamaño)]

    for bi in range(N):
        for bj in range(N):
            for bk in range(N):
                # Multiplicar el bloque (bi, bk) de matriz1 con el bloque (bk, bj) de matriz2
                for i in range(M):
                    for j in range(M):
                        for k in range(M):
                            resultado[bi*M + i][bj*M + j] += matriz1[bi*M + i][bk*M + k] * matriz2[bk*M + k][bj*M + j]

    return resultado

# Parámetros
N = 2  # Número de bloques
M = 2  # Tamaño de cada bloque

# Generar matrices aleatorias por bloques
matriz1 = generar_matriz_aleatoria_por_bloques(N, M)
matriz2 = generar_matriz_aleatoria_por_bloques(N, M)

# Convertir las matrices de numpy a listas de listas para la multiplicación
matriz1_lista = matriz1.tolist()
matriz2_lista = matriz2.tolist()

# Multiplicar las matrices por bloques
resultado = multiplicar_bloques(matriz1_lista, matriz2_lista, N, M)

# Imprimir las matrices y el resultado
print("Matriz 1:")
for fila in matriz1_lista:
    print(fila)

print("\nMatriz 2:")
for fila in matriz2_lista:
    print(fila)

print("\nResultado de la multiplicación:")
for fila in resultado:
    print(fila)

Matriz 1:
[0.07368067392773159, 0.568656169013507, 0.6923962818312416, 0.22843017069321325]
[0.4537727073772104, 0.1934571091621874, 0.26303365817345903, 0.2504001876060584]
[0.9820869178340577, 0.354617187614927, 0.5158483216239732, 0.4882846323441635]
[0.19960047507114864, 0.356679219412936, 0.2615320505830151, 0.8919948285622803]

Matriz 2:
[0.8906695374328517, 0.9545773167504982, 0.1304780366177083, 0.7247827453772269]
[0.7043512039925688, 0.7390781834934741, 0.699648087613977, 0.1549859119738125]
[0.15046884275656536, 0.5078879408501127, 0.9978659577786754, 0.45387220721470845]
[0.42075810330055574, 0.7691659625108221, 0.45166594762343804, 0.5778824712099756]

Resultado de la multiplicación:
[0.666456701681013, 1.0179757023804634, 1.2015657192748102, 0.587801396325792]
[0.6853595532932362, 0.9023319865831296, 0.5701288396513975, 0.6229553013336081]
[1.4075587596477628, 1.8371327827766344, 1.1115370306802719, 1.2830606670472906]
[0.8436719776503758, 1.273068950991822, 0.93945103151

**3.  Realizar un test para verificar que los resultados de los algoritmos 1 y 2 son iguales. Para unir una matriz en bloques en un solo elemento numpy se puede utilizar la función numpy.block. Así se puede utilizar el código del punto 1 en el punto 3. En el test se puede utilizar la función np.dot**

In [3]:
def generar_matriz_aleatoria(tamaño):
    """
    Genera una matriz cuadrada de tamaño dado con valores aleatorios entre 0 y 1.
    """
    return np.random.rand(tamaño, tamaño)

def multiplicar_matrices(matriz1, matriz2):
    """
    Multiplica dos matrices cuadradas de igual tamaño sin usar numpy.
    """
    tamaño = len(matriz1)
    resultado = [[0] * tamaño for _ in range(tamaño)]

    for i in range(tamaño):
        for j in range(tamaño):
            for k in range(tamaño):
                resultado[i][j] += matriz1[i][k] * matriz2[k][j]

    return resultado

def generar_matriz_aleatoria_por_bloques(N, M):
    """
    Genera una matriz NxN bloques de MxM unidades con valores aleatorios entre 0 y 1.
    """
    return np.random.rand(N * M, N * M)

def multiplicar_bloques(matriz1, matriz2, N, M):
    """
    Multiplica matrices usando el enfoque por bloques.
    """
    tamaño = N * M
    resultado = [[0] * tamaño for _ in range(tamaño)]

    for bi in range(N):
        for bj in range(N):
            for bk in range(N):
                for i in range(M):
                    for j in range(M):
                        for k in range(M):
                            resultado[bi*M + i][bj*M + j] += matriz1[bi*M + i][bk*M + k] * matriz2[bk*M + k][bj*M + j]

    return resultado

def test_multiplicacion():
    # Parámetros
    N = 2  # Número de bloques
    M = 2  # Tamaño de cada bloque
    tamaño = N * M

    # Generar matrices aleatorias
    matriz1 = generar_matriz_aleatoria(tamaño)
    matriz2 = generar_matriz_aleatoria(tamaño)

    # Convertir las matrices de numpy a listas de listas para la multiplicación clásica
    matriz1_lista = matriz1.tolist()
    matriz2_lista = matriz2.tolist()

    # Multiplicar las matrices utilizando el algoritmo clásico
    resultado_clasico = multiplicar_matrices(matriz1_lista, matriz2_lista)

    # Convertir el resultado clásico a numpy para comparación
    resultado_clasico_np = np.array(resultado_clasico)

    # Multiplicar las matrices utilizando el algoritmo por bloques
    matriz1_bloques = matriz1.tolist()
    matriz2_bloques = matriz2.tolist()
    resultado_bloques = multiplicar_bloques(matriz1_bloques, matriz2_bloques, N, M)

    # Convertir el resultado por bloques a numpy para comparación
    resultado_bloques_np = np.array(resultado_bloques)

    # Usar np.allclose para comparar las matrices resultantes
    if np.allclose(resultado_clasico_np, resultado_bloques_np):
        print("Los resultados de ambas multiplicaciones son iguales.")
    else:
        print("Los resultados de ambas multiplicaciones son diferentes.")

    # Imprimir resultados para verificación
    print("\nResultado usando el algoritmo clásico:")
    print(resultado_clasico_np)

    print("\nResultado usando el algoritmo por bloques:")
    print(resultado_bloques_np)

# Ejecutar el test
test_multiplicacion()

Los resultados de ambas multiplicaciones son iguales.

Resultado usando el algoritmo clásico:
[[0.61688302 1.42051726 1.55957869 1.29991244]
 [0.34801874 1.11821099 1.18338243 0.8544941 ]
 [0.43856449 1.43940743 1.1420602  1.08590491]
 [0.64208713 1.4890366  1.7315707  1.36256459]]

Resultado usando el algoritmo por bloques:
[[0.61688302 1.42051726 1.55957869 1.29991244]
 [0.34801874 1.11821099 1.18338243 0.8544941 ]
 [0.43856449 1.43940743 1.1420602  1.08590491]
 [0.64208713 1.4890366  1.7315707  1.36256459]]
